/**
 * @fileoverview Barrel builder utilities for splitting large files.
 * @module shared/compiler/split-large-file-helpers/barrel-builder
 */

/**
 * Construye contenido del barrel
 */
export function buildBarrelContent(analysis, groupPlans, style) {
    const lines = [];

    lines.push(`/**`);
    lines.push(` * @fileoverview Barrel/Coordinador - Auto-generated by split_large_file`);
    lines.push(` *`);
    lines.push(` * Este archivo re-exporta desde los módulos divididos.`);
    lines.push(` * Mantiene compatibilidad con imports existentes.`);
    lines.push(` */`);
    lines.push('');

    // Re-exportar desde cada grupo
    for (const group of groupPlans) {
        const relativePath = `./${group.newFilePath.split('/').pop()}`;

        if (group.exports.length > 0) {
            if (style === 're-export') {
                lines.push(`export { ${group.exports.join(', ')} } from '${relativePath}';`);
            } else {
                lines.push(`export * from '${relativePath}';`);
            }
        }
    }

    // Agregar imports originales que no se movieron
    lines.push('');
    lines.push('// Original imports preservation');
    for (const imp of analysis.imports) {
        lines.push(imp.fullMatch);
    }

    return lines.join('\n');
}
